### ISSUE TITLE
Some issues on sites

### ISSUE THREAD

**Issue by Poopooracoocoo** [Snazzah/MediaSessionMaster#2]
Squidradio - no effect. No metadata.

SoundCloud now supports media session API quite well. The extension breaks SoundCloud's own support for it.

Picarto - no effect. No metadata.

Vine - no effect. No metadata. 

Spotify already supports the media session API well so I didn't bother to test what happens with this extension. 

Thank you for this extension!

**Comment by Snazzah** [comment]
Fixed most of this in v1.2.1
